// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSubmitInfo = "submit_infos"

// SubmitInfo 提交信息
type SubmitInfo struct {
	ID        int32     `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:提交记录唯一ID" json:"id"`                        // 提交记录唯一ID
	SubmitID  string    `gorm:"column:submit_id;type:varchar(20);not null;comment:提交ID" json:"submit_id"`                           // 提交ID
	TaskID    string    `gorm:"column:task_id;type:varchar(50);not null;comment:任务ID" json:"task_id"`                               // 任务ID
	AppID     uint64    `gorm:"column:app_id;type:bigint;not null;comment:创建人" json:"app_id"`                                       // 创建人
	Language  string    `gorm:"column:language;type:varchar(10);not null;comment:提交语言" json:"language"`                             // 提交语言
	Code      *string   `gorm:"column:code;type:text;comment:代码" json:"code"`                                                       // 代码
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:提交时间" json:"created_at"` // 提交时间
}

// TableName SubmitInfo's table name
func (*SubmitInfo) TableName() string {
	return TableNameSubmitInfo
}
