// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaskInfo = "task_infos"

// TaskInfo 任务信息
type TaskInfo struct {
	ID        string    `gorm:"column:id;type:varchar(50);primaryKey;comment:任务ID" json:"id"`                                       // 任务ID
	Status    byte      `gorm:"column:status;type:tinyint;not null;comment:任务状态 0 - 待执行 1 - 执行中 2 - 执行成功 3 - 执行失败" json:"status"`   // 任务状态 0 - 待执行 1 - 执行中 2 - 执行成功 3 - 执行失败
	Output    *string   `gorm:"column:output;type:text;comment:执行结果" json:"output"`                                                 // 执行结果
	ErrOutput *string   `gorm:"column:err_output;type:text;comment:错误输出" json:"err_output"`                                         // 错误输出
	Memory    *int64   `gorm:"column:memory;type:bigint;comment:内存使用" json:"memory"`                                               // 内存使用
	Time      *int64   `gorm:"column:time;type:bigint;comment:执行时间" json:"time"`                                                   // 执行时间
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName TaskInfo's table name
func (*TaskInfo) TableName() string {
	return TableNameTaskInfo
}
