// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Wenrh2004/sandbox/internal/task/infrastructure/model"
)

func newTaskInfo(db *gorm.DB, opts ...gen.DOOption) taskInfo {
	_taskInfo := taskInfo{}

	_taskInfo.taskInfoDo.UseDB(db, opts...)
	_taskInfo.taskInfoDo.UseModel(&model.TaskInfo{})

	tableName := _taskInfo.taskInfoDo.TableName()
	_taskInfo.ALL = field.NewAsterisk(tableName)
	_taskInfo.ID = field.NewString(tableName, "id")
	_taskInfo.Language = field.NewString(tableName, "language")
	_taskInfo.Status = field.NewField(tableName, "status")
	_taskInfo.Output = field.NewString(tableName, "output")
	_taskInfo.ErrOutput = field.NewString(tableName, "err_output")
	_taskInfo.Memory = field.NewInt64(tableName, "memory")
	_taskInfo.Time = field.NewInt64(tableName, "time")
	_taskInfo.CreatedAt = field.NewTime(tableName, "created_at")
	_taskInfo.UpdatedAt = field.NewTime(tableName, "updated_at")

	_taskInfo.fillFieldMap()

	return _taskInfo
}

// taskInfo 任务信息
type taskInfo struct {
	taskInfoDo

	ALL       field.Asterisk
	ID        field.String // 任务ID
	Language  field.String
	Status    field.Field  // 任务状态 0 - 待执行 1 - 执行中 2 - 执行成功 3 - 执行失败
	Output    field.String // 执行结果
	ErrOutput field.String // 错误输出
	Memory    field.Int64  // 内存使用
	Time      field.Int64  // 执行时间
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (t taskInfo) Table(newTableName string) *taskInfo {
	t.taskInfoDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t taskInfo) As(alias string) *taskInfo {
	t.taskInfoDo.DO = *(t.taskInfoDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *taskInfo) updateTableName(table string) *taskInfo {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.Language = field.NewString(table, "language")
	t.Status = field.NewField(table, "status")
	t.Output = field.NewString(table, "output")
	t.ErrOutput = field.NewString(table, "err_output")
	t.Memory = field.NewInt64(table, "memory")
	t.Time = field.NewInt64(table, "time")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *taskInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *taskInfo) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 9)
	t.fieldMap["id"] = t.ID
	t.fieldMap["language"] = t.Language
	t.fieldMap["status"] = t.Status
	t.fieldMap["output"] = t.Output
	t.fieldMap["err_output"] = t.ErrOutput
	t.fieldMap["memory"] = t.Memory
	t.fieldMap["time"] = t.Time
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t taskInfo) clone(db *gorm.DB) taskInfo {
	t.taskInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t taskInfo) replaceDB(db *gorm.DB) taskInfo {
	t.taskInfoDo.ReplaceDB(db)
	return t
}

type taskInfoDo struct{ gen.DO }

type ITaskInfoDo interface {
	gen.SubQuery
	Debug() ITaskInfoDo
	WithContext(ctx context.Context) ITaskInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITaskInfoDo
	WriteDB() ITaskInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITaskInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITaskInfoDo
	Not(conds ...gen.Condition) ITaskInfoDo
	Or(conds ...gen.Condition) ITaskInfoDo
	Select(conds ...field.Expr) ITaskInfoDo
	Where(conds ...gen.Condition) ITaskInfoDo
	Order(conds ...field.Expr) ITaskInfoDo
	Distinct(cols ...field.Expr) ITaskInfoDo
	Omit(cols ...field.Expr) ITaskInfoDo
	Join(table schema.Tabler, on ...field.Expr) ITaskInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITaskInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITaskInfoDo
	Group(cols ...field.Expr) ITaskInfoDo
	Having(conds ...gen.Condition) ITaskInfoDo
	Limit(limit int) ITaskInfoDo
	Offset(offset int) ITaskInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskInfoDo
	Unscoped() ITaskInfoDo
	Create(values ...*model.TaskInfo) error
	CreateInBatches(values []*model.TaskInfo, batchSize int) error
	Save(values ...*model.TaskInfo) error
	First() (*model.TaskInfo, error)
	Take() (*model.TaskInfo, error)
	Last() (*model.TaskInfo, error)
	Find() ([]*model.TaskInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TaskInfo, err error)
	FindInBatches(result *[]*model.TaskInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TaskInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITaskInfoDo
	Assign(attrs ...field.AssignExpr) ITaskInfoDo
	Joins(fields ...field.RelationField) ITaskInfoDo
	Preload(fields ...field.RelationField) ITaskInfoDo
	FirstOrInit() (*model.TaskInfo, error)
	FirstOrCreate() (*model.TaskInfo, error)
	FindByPage(offset int, limit int) (result []*model.TaskInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITaskInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t taskInfoDo) Debug() ITaskInfoDo {
	return t.withDO(t.DO.Debug())
}

func (t taskInfoDo) WithContext(ctx context.Context) ITaskInfoDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t taskInfoDo) ReadDB() ITaskInfoDo {
	return t.Clauses(dbresolver.Read)
}

func (t taskInfoDo) WriteDB() ITaskInfoDo {
	return t.Clauses(dbresolver.Write)
}

func (t taskInfoDo) Session(config *gorm.Session) ITaskInfoDo {
	return t.withDO(t.DO.Session(config))
}

func (t taskInfoDo) Clauses(conds ...clause.Expression) ITaskInfoDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t taskInfoDo) Returning(value interface{}, columns ...string) ITaskInfoDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t taskInfoDo) Not(conds ...gen.Condition) ITaskInfoDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t taskInfoDo) Or(conds ...gen.Condition) ITaskInfoDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t taskInfoDo) Select(conds ...field.Expr) ITaskInfoDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t taskInfoDo) Where(conds ...gen.Condition) ITaskInfoDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t taskInfoDo) Order(conds ...field.Expr) ITaskInfoDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t taskInfoDo) Distinct(cols ...field.Expr) ITaskInfoDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t taskInfoDo) Omit(cols ...field.Expr) ITaskInfoDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t taskInfoDo) Join(table schema.Tabler, on ...field.Expr) ITaskInfoDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t taskInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITaskInfoDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t taskInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) ITaskInfoDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t taskInfoDo) Group(cols ...field.Expr) ITaskInfoDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t taskInfoDo) Having(conds ...gen.Condition) ITaskInfoDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t taskInfoDo) Limit(limit int) ITaskInfoDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t taskInfoDo) Offset(offset int) ITaskInfoDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t taskInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskInfoDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t taskInfoDo) Unscoped() ITaskInfoDo {
	return t.withDO(t.DO.Unscoped())
}

func (t taskInfoDo) Create(values ...*model.TaskInfo) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t taskInfoDo) CreateInBatches(values []*model.TaskInfo, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t taskInfoDo) Save(values ...*model.TaskInfo) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t taskInfoDo) First() (*model.TaskInfo, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskInfo), nil
	}
}

func (t taskInfoDo) Take() (*model.TaskInfo, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskInfo), nil
	}
}

func (t taskInfoDo) Last() (*model.TaskInfo, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskInfo), nil
	}
}

func (t taskInfoDo) Find() ([]*model.TaskInfo, error) {
	result, err := t.DO.Find()
	return result.([]*model.TaskInfo), err
}

func (t taskInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TaskInfo, err error) {
	buf := make([]*model.TaskInfo, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t taskInfoDo) FindInBatches(result *[]*model.TaskInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t taskInfoDo) Attrs(attrs ...field.AssignExpr) ITaskInfoDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t taskInfoDo) Assign(attrs ...field.AssignExpr) ITaskInfoDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t taskInfoDo) Joins(fields ...field.RelationField) ITaskInfoDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t taskInfoDo) Preload(fields ...field.RelationField) ITaskInfoDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t taskInfoDo) FirstOrInit() (*model.TaskInfo, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskInfo), nil
	}
}

func (t taskInfoDo) FirstOrCreate() (*model.TaskInfo, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskInfo), nil
	}
}

func (t taskInfoDo) FindByPage(offset int, limit int) (result []*model.TaskInfo, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t taskInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t taskInfoDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t taskInfoDo) Delete(models ...*model.TaskInfo) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *taskInfoDo) withDO(do gen.Dao) *taskInfoDo {
	t.DO = *do.(*gen.DO)
	return t
}
